# Generated by Django 5.0.6 on 2024-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
