# Generated by Django 5.0.6 on 2024-07-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dep_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
