# Generated by Django 5.0.6 on 2024-07-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_dep_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="btc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="usd",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
