# Generated by Django 5.0.6 on 2024-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_btc_user_usd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("qr_code", models.ImageField(blank=True, null=True, upload_to="QR/")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
