# Generated by Django 5.0.6 on 2024-07-26 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("completed", "completed"),
                            ("subscribe", "subscribe"),
                            ("unsubscribe", "unsubscribe"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="transactions",
            field=models.ManyToManyField(blank=True, to="user.transaction"),
        ),
    ]
