# Generated by Django 5.0.6 on 2024-07-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_transaction_user_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("completed", "completed")],
                default="pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("subscribe", "subscribe"),
                    ("unsubscribe", "unsubscribe"),
                ],
                max_length=255,
            ),
        ),
    ]
