# Generated by Django 5.0.6 on 2024-07-26 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_transaction_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otpt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
