# Generated by Django 5.0.6 on 2024-07-27 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_remove_user_city_remove_user_postal_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("min_deposit", models.FloatField(default=0)),
                ("max_deposit", models.FloatField(default=0)),
                ("duration", models.IntegerField(default=0)),
                (
                    "duration_type",
                    models.CharField(
                        choices=[("weeks", "weeks"), ("months", "months")],
                        max_length=255,
                    ),
                ),
                ("interest", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Investment Plan",
                "verbose_name_plural": "Investment Plans",
                "ordering": ["min_deposit"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("interest", models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="plans",
            field=models.ManyToManyField(blank=True, to="user.plan"),
        ),
    ]
