# Generated by Django 5.0.6 on 2024-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_investmentplan_plan_user_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentplan",
            name="interest",
            field=models.IntegerField(default=0),
        ),
    ]
