# Generated by Django 5.0.6 on 2024-07-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_investmentplan_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="investment_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.investmentplan",
            ),
        ),
    ]
