# Generated by Django 5.0.6 on 2024-07-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_plan_investment_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_medium",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
