# Generated by Django 5.0.6 on 2024-07-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_transaction_transaction_medium"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="email_status",
            field=models.CharField(
                choices=[("not sent", "not sent"), ("sent", "sent")],
                default="not sent",
                max_length=255,
            ),
        ),
    ]
