# Generated by Django 5.0.6 on 2024-07-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_transaction_email_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Address",
            new_name="TransactionDetail",
        ),
    ]
