# Generated by Django 5.0.6 on 2024-07-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_rename_address_transactiondetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(default="support@domain.com", max_length=254),
                ),
                (
                    "support_phone",
                    models.CharField(default="+1234567890", max_length=255),
                ),
                (
                    "concierge_phone",
                    models.CharField(default="+1234567890", max_length=255),
                ),
                (
                    "expert_phone",
                    models.CharField(default="+1234567890", max_length=255),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="bank_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="bank_sort_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="cash_app_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="paypal_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="zelle_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transactiondetail",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
