# Generated by Django 4.2.14 on 2024-08-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_sitesetting_transactiondetail_bank_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactiondetail",
            old_name="bank_number",
            new_name="bank_account_name",
        ),
        migrations.RenameField(
            model_name="transactiondetail",
            old_name="bank_sort_code",
            new_name="bank_account_number",
        ),
        migrations.RenameField(
            model_name="transactiondetail",
            old_name="cash_app_info",
            new_name="cashapp_account_name",
        ),
        migrations.RenameField(
            model_name="transactiondetail",
            old_name="paypal_info",
            new_name="cashapp_username",
        ),
        migrations.RenameField(
            model_name="transactiondetail",
            old_name="zelle_info",
            new_name="paypal_email",
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="zelle_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
