# Generated by Django 4.2.14 on 2024-08-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user",
            "0017_rename_bank_number_transactiondetail_bank_account_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="domain",
            field=models.CharField(default="chestgold.net", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="support_email",
            field=models.EmailField(default="support@chestgold.net", max_length=254),
        ),
    ]
