# Generated by Django 4.2.14 on 2024-08-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_sitesetting_domain_alter_sitesetting_support_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forgot_password_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="forgot_password_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
