# Generated by Django 4.2.14 on 2024-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_user_forgot_password_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="forgot_password_code",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
