# Generated by Django 4.2.14 on 2024-08-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_alter_user_forgot_password_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="concierge_phone",
            field=models.CharField(
                blank=True, default="+1234567890", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="domain",
            field=models.CharField(
                blank=True, default="chestgold.net", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="expert_phone",
            field=models.CharField(
                blank=True, default="+1234567890", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="support_email",
            field=models.EmailField(
                blank=True, default="support@chestgold.net", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="support_phone",
            field=models.CharField(
                blank=True, default="+1234567890", max_length=255, null=True
            ),
        ),
    ]
