# Generated by Django 4.2.14 on 2024-08-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_alter_sitesetting_concierge_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="domain",
            field=models.CharField(default="chestgold.net", max_length=255),
        ),
    ]
